# 檢視與處理 Outliers
### 為何會有 outliers, 常見的 outlier 原因
* 未知值，隨意填補 (約定俗成的代入)，如年齡常見 0,999
* 可能的錯誤紀錄/手誤/系統性錯誤，如某本書在某筆訂單的銷售量 = 1000 本

# [作業目標]
- 依照下列提示與引導, 以幾種不同的方式, 檢視可能的離群值

# [作業重點]
- 從原始資料篩選可能的欄位, 看看那些欄位可能有離群值 (In[3], Out[3])
- 繪製目標值累積密度函數(ECDF)的圖形, 和常態分布的累積密度函數對比, 以確認是否有離群值的情形 (In[6], Out[6], In[7], Out[7])

In [2]:
# Import 需要的套件
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

# 設定 data_path
dir_data = '../data'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)
app_train.head()

Path of read in data: ../data/application_train.csv

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

## 請參考 HomeCredit_columns_description.csv 的欄位說明，觀察並列出三個你覺得可能有 outlier 的欄位並解釋可能的原因

In [4]:
# 先篩選數值型的欄位
"""
YOUR CODE HERE, fill correct data types (for example str, float, int, ...)
"""
dtypes_select=['int64','float64']
numeric_columns=list(app_train.select_dtypes(include=dtypes_select))

#numeric_columns = list(app_train.columns[list(app_train.dtypes.isin(dtype_select))])

## dtypes.isin必須接收dtype類型

In [8]:
# 再把只有 2 值 (通常是 0,1) 的欄位去掉
numeric_columns = list(app_train[numeric_columns].columns[list(app_train[numeric_columns].apply(lambda x:len(x.unique())!=2 ))])
print("Numbers of remain columns %i" % len(numeric_columns))

Numbers of remain columns 73

In [11]:
# 檢視這些欄位的數值範圍

df = pd.DataFrame(,['Max','Min'])

for col in numeric_columns:
    """
    Your CODE HERE, make the box plot
    """

#    plt.show()

Max:  <bound method Series.max of 0         100002
1         100003
2         100004
3         100006
4         100007
5         100008
6         100009
7         100010
8         100011
9         100012
10        100014
11        100015
12        100016
13        100017
14        100018
15        100019
16        100020
17        100021
18        100022
19        100023
20        100024
21        100025
22        100026
23        100027
24        100029
25        100030
26        100031
27        100032
28        100033
29        100034
           ...
307481    456225
307482    456226
307483    456227
307484    456228
307485    456229
307486    456230
307487    456231
307488    456232
307489    456233
307490    456234
307491    456235
307492    456236
307493    456237
307494    456238
307495    456239
307496    456240
307497    456241
307498    456242
307499    456243
307500    456244
307501    456245
307502    456246
307503    456247
307504    456248
307505    456249
307506    456251
307507    456252
307508    456253
307509    456254
307510    456255
Name: SK_ID_CURR, Length: 307511, dtype: int64>
Min:  <bound method Series.min of 0         100002
1         100003
2         100004
3         100006
4         100007
5         100008
6         100009
7         100010
8         100011
9         100012
10        100014
11        100015
12        100016
13        100017
14        100018
15        100019
16        100020
17        100021
18        100022
19        100023
20        100024
21        100025
22        100026
23        100027
24        100029
25        100030
26        100031
27        100032
28        100033
29        100034
           ...
307481    456225
307482    456226
307483    456227
307484    456228
307485    456229
307486    456230
307487    456231
307488    456232
307489    456233
307490    456234
307491    456235
307492    456236
307493    456237
307494    456238
307495    456239
307496    456240
307497    456241
307498    456242
307499    456243
307500    456244
307501    456245
307502    456246
307503    456247
307504    456248
307505    456249
307506    456251
307507    456252
307508    456253
307509    456254
307510    456255
Name: SK_ID_CURR, Length: 307511, dtype: int64>
Max:  <bound method Series.max of 0         0
1         0
2         0
3         0
4         0
5         0
6         1
7         0
8         0
9         0
10        1
11        0
12        0
13        1
14        0
15        0
16        0
17        1
18        0
19        1
20        0
21        1
22        1
23        0
24        2
25        0
26        0
27        1
28        0
29        0
         ..
307481    0
307482    0
307483    0
307484    0
307485    1
307486    1
307487    0
307488    0
307489    0
307490    0
307491    2
307492    0
307493    0
307494    1
307495    0
307496    0
307497    0
307498    0
307499    0
307500    0
307501    3
307502    1
307503    0
307504    0
307505    0
307506    0
307507    0
307508    0
307509    0
307510    0
Name: CNT_CHILDREN, Length: 307511, dtype: int64>
Min:  <bound method Series.min of 0         0
1         0
2         0
3         0
4         0
5         0
6         1
7         0
8         0
9         0
10        1
11        0
12        0
13        1
14        0
15        0
16        0
17        1
18        0
19        1
20        0
21        1
22        1
23        0
24        2
25        0
26        0
27        1
28        0
29        0
         ..
307481    0
307482    0
307483    0
307484    0
307485    1
307486    1
307487    0
307488    0
307489    0
307490    0
307491    2
307492    0
307493    0
307494    1
307495    0
307496    0
307497    0
307498    0
307499    0
307500    0
307501    3
307502    1
307503    0
307504    0
307505    0
307506    0
307507    0
307508    0
307509    0
307510    0
Name: CNT_CHILDREN, Length: 307511, dtype: int64>
Max:  <bound method Series.max of 0         202500.000
1         270000.000
2          67500.000
3         135000.000
4         121500.000
5          99000.000
6         171000.000
7         360000.000
8         112500.000
9         135000.000
10        112500.000
11         38419.155
12         67500.000
13        225000.000
14        189000.000
15        157500.000
16        108000.000
17         81000.000
18        112500.000
19         90000.000
20        135000.000
21        202500.000
22        450000.000
23         83250.000
24        135000.000
25         90000.000
26        112500.000
27        112500.000
28        270000.000
29         90000.000
             ...
307481    225000.000
307482    225000.000
307483     99000.000
307484    540000.000
307485    270000.000
307486    292500.000
307487    117000.000
307488    157500.000
307489    225000.000
307490     81000.000
307491     90000.000
307492    585000.000
307493    135000.000
307494    270000.000
307495    180000.000
307496    360000.000
307497    180000.000
307498    198000.000
307499     81000.000
307500    261000.000
307501     81000.000
307502     94500.000
307503    112500.000
307504    153000.000
307505    112500.000
307506    157500.000
307507     72000.000
307508    153000.000
307509    171000.000
307510    157500.000
Name: AMT_INCOME_TOTAL, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         202500.000
1         270000.000
2          67500.000
3         135000.000
4         121500.000
5          99000.000
6         171000.000
7         360000.000
8         112500.000
9         135000.000
10        112500.000
11         38419.155
12         67500.000
13        225000.000
14        189000.000
15        157500.000
16        108000.000
17         81000.000
18        112500.000
19         90000.000
20        135000.000
21        202500.000
22        450000.000
23         83250.000
24        135000.000
25         90000.000
26        112500.000
27        112500.000
28        270000.000
29         90000.000
             ...
307481    225000.000
307482    225000.000
307483     99000.000
307484    540000.000
307485    270000.000
307486    292500.000
307487    117000.000
307488    157500.000
307489    225000.000
307490     81000.000
307491     90000.000
307492    585000.000
307493    135000.000
307494    270000.000
307495    180000.000
307496    360000.000
307497    180000.000
307498    198000.000
307499     81000.000
307500    261000.000
307501     81000.000
307502     94500.000
307503    112500.000
307504    153000.000
307505    112500.000
307506    157500.000
307507     72000.000
307508    153000.000
307509    171000.000
307510    157500.000
Name: AMT_INCOME_TOTAL, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0          406597.5
1         1293502.5
2          135000.0
3          312682.5
4          513000.0
5          490495.5
6         1560726.0
7         1530000.0
8         1019610.0
9          405000.0
10         652500.0
11         148365.0
12          80865.0
13         918468.0
14         773680.5
15         299772.0
16         509602.5
17         270000.0
18         157500.0
19         544491.0
20         427500.0
21        1132573.5
22         497520.0
23         239850.0
24         247500.0
25         225000.0
26         979992.0
27         327024.0
28         790830.0
29         180000.0
            ...
307481     297000.0
307482     500566.5
307483     247275.0
307484     545040.0
307485     180000.0
307486     355536.0
307487    1071909.0
307488     135000.0
307489     521280.0
307490     135000.0
307491    1078200.0
307492    1575000.0
307493     946764.0
307494     479700.0
307495     808650.0
307496     337500.0
307497     270126.0
307498    1312110.0
307499     225000.0
307500    1303812.0
307501     269550.0
307502     225000.0
307503     345510.0
307504     331920.0
307505     225000.0
307506     254700.0
307507     269550.0
307508     677664.0
307509     370107.0
307510     675000.0
Name: AMT_CREDIT, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0          406597.5
1         1293502.5
2          135000.0
3          312682.5
4          513000.0
5          490495.5
6         1560726.0
7         1530000.0
8         1019610.0
9          405000.0
10         652500.0
11         148365.0
12          80865.0
13         918468.0
14         773680.5
15         299772.0
16         509602.5
17         270000.0
18         157500.0
19         544491.0
20         427500.0
21        1132573.5
22         497520.0
23         239850.0
24         247500.0
25         225000.0
26         979992.0
27         327024.0
28         790830.0
29         180000.0
            ...
307481     297000.0
307482     500566.5
307483     247275.0
307484     545040.0
307485     180000.0
307486     355536.0
307487    1071909.0
307488     135000.0
307489     521280.0
307490     135000.0
307491    1078200.0
307492    1575000.0
307493     946764.0
307494     479700.0
307495     808650.0
307496     337500.0
307497     270126.0
307498    1312110.0
307499     225000.0
307500    1303812.0
307501     269550.0
307502     225000.0
307503     345510.0
307504     331920.0
307505     225000.0
307506     254700.0
307507     269550.0
307508     677664.0
307509     370107.0
307510     675000.0
Name: AMT_CREDIT, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         24700.5
1         35698.5
2          6750.0
3         29686.5
4         21865.5
5         27517.5
6         41301.0
7         42075.0
8         33826.5
9         20250.0
10        21177.0
11        10678.5
12         5881.5
13        28966.5
14        32778.0
15        20160.0
16        26149.5
17        13500.0
18         7875.0
19        17563.5
20        21375.0
21        37561.5
22        32521.5
23        23850.0
24        12703.5
25        11074.5
26        27076.5
27        23827.5
28        57676.5
29         9000.0
           ...
307481    19975.5
307482    34969.5
307483    16479.0
307484    35617.5
307485     9000.0
307486    18283.5
307487    31473.0
307488    13351.5
307489    23089.5
307490     9148.5
307491    31522.5
307492    43443.0
307493    37678.5
307494    46858.5
307495    23773.5
307496    16875.0
307497    12028.5
307498    52168.5
307499    12694.5
307500    35982.0
307501    11871.0
307502    10620.0
307503    17770.5
307504    16096.5
307505    22050.0
307506    27558.0
307507    12001.5
307508    29979.0
307509    20205.0
307510    49117.5
Name: AMT_ANNUITY, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         24700.5
1         35698.5
2          6750.0
3         29686.5
4         21865.5
5         27517.5
6         41301.0
7         42075.0
8         33826.5
9         20250.0
10        21177.0
11        10678.5
12         5881.5
13        28966.5
14        32778.0
15        20160.0
16        26149.5
17        13500.0
18         7875.0
19        17563.5
20        21375.0
21        37561.5
22        32521.5
23        23850.0
24        12703.5
25        11074.5
26        27076.5
27        23827.5
28        57676.5
29         9000.0
           ...
307481    19975.5
307482    34969.5
307483    16479.0
307484    35617.5
307485     9000.0
307486    18283.5
307487    31473.0
307488    13351.5
307489    23089.5
307490     9148.5
307491    31522.5
307492    43443.0
307493    37678.5
307494    46858.5
307495    23773.5
307496    16875.0
307497    12028.5
307498    52168.5
307499    12694.5
307500    35982.0
307501    11871.0
307502    10620.0
307503    17770.5
307504    16096.5
307505    22050.0
307506    27558.0
307507    12001.5
307508    29979.0
307509    20205.0
307510    49117.5
Name: AMT_ANNUITY, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0          351000.0
1         1129500.0
2          135000.0
3          297000.0
4          513000.0
5          454500.0
6         1395000.0
7         1530000.0
8          913500.0
9          405000.0
10         652500.0
11         135000.0
12          67500.0
13         697500.0
14         679500.0
15         247500.0
16         387000.0
17         270000.0
18         157500.0
19         454500.0
20         427500.0
21         927000.0
22         450000.0
23         225000.0
24         247500.0
25         225000.0
26         702000.0
27         270000.0
28         675000.0
29         180000.0
            ...
307481     297000.0
307482     472500.0
307483     225000.0
307484     450000.0
307485     180000.0
307486     270000.0
307487     936000.0
307488     135000.0
307489     450000.0
307490     135000.0
307491     900000.0
307492    1575000.0
307493     765000.0
307494     450000.0
307495     675000.0
307496     337500.0
307497     193500.0
307498    1125000.0
307499     225000.0
307500    1138500.0
307501     225000.0
307502     225000.0
307503     247500.0
307504     225000.0
307505     225000.0
307506     225000.0
307507     225000.0
307508     585000.0
307509     319500.0
307510     675000.0
Name: AMT_GOODS_PRICE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0          351000.0
1         1129500.0
2          135000.0
3          297000.0
4          513000.0
5          454500.0
6         1395000.0
7         1530000.0
8          913500.0
9          405000.0
10         652500.0
11         135000.0
12          67500.0
13         697500.0
14         679500.0
15         247500.0
16         387000.0
17         270000.0
18         157500.0
19         454500.0
20         427500.0
21         927000.0
22         450000.0
23         225000.0
24         247500.0
25         225000.0
26         702000.0
27         270000.0
28         675000.0
29         180000.0
            ...
307481     297000.0
307482     472500.0
307483     225000.0
307484     450000.0
307485     180000.0
307486     270000.0
307487     936000.0
307488     135000.0
307489     450000.0
307490     135000.0
307491     900000.0
307492    1575000.0
307493     765000.0
307494     450000.0
307495     675000.0
307496     337500.0
307497     193500.0
307498    1125000.0
307499     225000.0
307500    1138500.0
307501     225000.0
307502     225000.0
307503     247500.0
307504     225000.0
307505     225000.0
307506     225000.0
307507     225000.0
307508     585000.0
307509     319500.0
307510     675000.0
Name: AMT_GOODS_PRICE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.018801
1         0.003541
2         0.010032
3         0.008019
4         0.028663
5         0.035792
6         0.035792
7         0.003122
8         0.018634
9         0.019689
10        0.022800
11        0.015221
12        0.031329
13        0.016612
14        0.010006
15        0.020713
16        0.018634
17        0.010966
18        0.046220
19        0.015221
20        0.015221
21        0.025164
22        0.020713
23        0.006296
24        0.026392
25        0.028663
26        0.018029
27        0.019101
28        0.046220
29        0.030755
            ...
307481    0.008575
307482    0.031329
307483    0.007330
307484    0.032561
307485    0.003813
307486    0.072508
307487    0.010147
307488    0.004960
307489    0.014464
307490    0.010147
307491    0.019101
307492    0.028663
307493    0.019689
307494    0.035792
307495    0.025164
307496    0.004960
307497    0.007020
307498    0.072508
307499    0.007020
307500    0.031329
307501    0.009175
307502    0.010966
307503    0.022800
307504    0.022625
307505    0.022800
307506    0.032561
307507    0.025164
307508    0.005002
307509    0.005313
307510    0.046220
Name: REGION_POPULATION_RELATIVE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.018801
1         0.003541
2         0.010032
3         0.008019
4         0.028663
5         0.035792
6         0.035792
7         0.003122
8         0.018634
9         0.019689
10        0.022800
11        0.015221
12        0.031329
13        0.016612
14        0.010006
15        0.020713
16        0.018634
17        0.010966
18        0.046220
19        0.015221
20        0.015221
21        0.025164
22        0.020713
23        0.006296
24        0.026392
25        0.028663
26        0.018029
27        0.019101
28        0.046220
29        0.030755
            ...
307481    0.008575
307482    0.031329
307483    0.007330
307484    0.032561
307485    0.003813
307486    0.072508
307487    0.010147
307488    0.004960
307489    0.014464
307490    0.010147
307491    0.019101
307492    0.028663
307493    0.019689
307494    0.035792
307495    0.025164
307496    0.004960
307497    0.007020
307498    0.072508
307499    0.007020
307500    0.031329
307501    0.009175
307502    0.010966
307503    0.022800
307504    0.022625
307505    0.022800
307506    0.032561
307507    0.025164
307508    0.005002
307509    0.005313
307510    0.046220
Name: REGION_POPULATION_RELATIVE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         -9461
1        -16765
2        -19046
3        -19005
4        -19932
5        -16941
6        -13778
7        -18850
8        -20099
9        -14469
10       -10197
11       -20417
12       -13439
13       -14086
14       -14583
15        -8728
16       -12931
17        -9776
18       -17718
19       -11348
20       -18252
21       -14815
22       -11146
23       -24827
24       -11286
25       -19334
26       -18724
27       -15948
28        -9994
29       -10341
          ...
307481   -20644
307482   -14106
307483   -24911
307484   -12847
307485   -11973
307486   -16010
307487   -23125
307488   -10092
307489   -16471
307490    -9874
307491   -10976
307492   -20965
307493   -17533
307494   -14958
307495   -20922
307496   -17345
307497   -16679
307498   -19102
307499   -16988
307500   -20390
307501   -12961
307502   -16063
307503   -11870
307504   -16705
307505   -24384
307506    -9327
307507   -20775
307508   -14966
307509   -11961
307510   -16856
Name: DAYS_BIRTH, Length: 307511, dtype: int64>
Min:  <bound method Series.min of 0         -9461
1        -16765
2        -19046
3        -19005
4        -19932
5        -16941
6        -13778
7        -18850
8        -20099
9        -14469
10       -10197
11       -20417
12       -13439
13       -14086
14       -14583
15        -8728
16       -12931
17        -9776
18       -17718
19       -11348
20       -18252
21       -14815
22       -11146
23       -24827
24       -11286
25       -19334
26       -18724
27       -15948
28        -9994
29       -10341
          ...
307481   -20644
307482   -14106
307483   -24911
307484   -12847
307485   -11973
307486   -16010
307487   -23125
307488   -10092
307489   -16471
307490    -9874
307491   -10976
307492   -20965
307493   -17533
307494   -14958
307495   -20922
307496   -17345
307497   -16679
307498   -19102
307499   -16988
307500   -20390
307501   -12961
307502   -16063
307503   -11870
307504   -16705
307505   -24384
307506    -9327
307507   -20775
307508   -14966
307509   -11961
307510   -16856
Name: DAYS_BIRTH, Length: 307511, dtype: int64>
Max:  <bound method Series.max of 0           -637
1          -1188
2           -225
3          -3039
4          -3038
5          -1588
6          -3130
7           -449
8         365243
9          -2019
10          -679
11        365243
12         -2717
13         -3028
14          -203
15         -1157
16         -1317
17          -191
18         -7804
19         -2038
20         -4286
21         -1652
22         -4306
23        365243
24          -746
25         -3494
26         -2628
27         -1234
28         -1796
29         -1010
           ...
307481     -3147
307482      -226
307483    365243
307484      -328
307485      -670
307486     -1185
307487    365243
307488     -1218
307489      -286
307490     -1928
307491     -1953
307492     -1618
307493     -2306
307494     -6573
307495     -7438
307496     -2178
307497     -1222
307498     -3689
307499     -8694
307500     -5326
307501     -1046
307502     -8736
307503      -399
307504     -7258
307505    365243
307506      -236
307507    365243
307508     -7921
307509     -4786
307510     -1262
Name: DAYS_EMPLOYED, Length: 307511, dtype: int64>
Min:  <bound method Series.min of 0           -637
1          -1188
2           -225

Name: NONLIVINGAREA_AVG, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0000
1         0.0098
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0000
13        0.0000
14        0.1001
15           NaN
16           NaN
17           NaN
18        0.0000
19           NaN
20        0.0000
21           NaN
22        0.0044
23        0.0007
24        0.0043
25        0.0000
26        0.0000
27           NaN
28           NaN
29        0.0061
           ...
307481       NaN
307482    0.0049
307483    0.0033
307484       NaN
307485       NaN
307486    0.1157
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0046
307496       NaN
307497       NaN
307498    0.0164
307499       NaN
307500    0.0032
307501    0.0000
307502       NaN
307503       NaN
307504       NaN
307505    0.0083
307506    0.1095
307507    0.0000
307508    0.0000
307509       NaN
307510    0.0000
Name: NONLIVINGAREA_AVG, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0252
1         0.0924
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0840
13        0.1502
14        0.3561
15           NaN
16           NaN
17           NaN
18        0.0284
19           NaN
20        0.0735
21           NaN
22        0.0924
23        0.1261
24        0.1460
25        0.0735
26        0.0168
27           NaN
28           NaN
29        0.1534
           ...
307481       NaN
307482    0.0399
307483    0.0084
307484       NaN
307485       NaN
307486    0.2006
307487       NaN
307488       NaN
307489    0.0116
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0756
307496       NaN
307497       NaN
307498    0.2101
307499       NaN
307500    0.1324
307501    0.0399
307502       NaN
307503       NaN
307504       NaN
307505    0.2248
307506    0.1008
307507    0.0252
307508    0.1050
307509    0.0126
307510    0.0756
Name: APARTMENTS_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0252
1         0.0924
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0840
13        0.1502
14        0.3561
15           NaN
16           NaN
17           NaN
18        0.0284
19           NaN
20        0.0735
21           NaN
22        0.0924
23        0.1261
24        0.1460
25        0.0735
26        0.0168
27           NaN
28           NaN
29        0.1534
           ...
307481       NaN
307482    0.0399
307483    0.0084
307484       NaN
307485       NaN
307486    0.2006
307487       NaN
307488       NaN
307489    0.0116
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0756
307496       NaN
307497       NaN
307498    0.2101
307499       NaN
307500    0.1324
307501    0.0399
307502       NaN
307503       NaN
307504       NaN
307505    0.2248
307506    0.1008
307507    0.0252
307508    0.1050
307509    0.0126
307510    0.0756
Name: APARTMENTS_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0383
1         0.0538
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.1010
14        0.1386
15           NaN
16           NaN
17           NaN
18        0.0640
19           NaN
20        0.0831
21           NaN
22        0.0825
23        0.0754
24        0.1509
25        0.0153
26        0.0092
27           NaN
28           NaN
29        0.0870
           ...
307481       NaN
307482    0.0417
307483    0.0000
307484       NaN
307485       NaN
307486    0.1990
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495       NaN
307496       NaN
307497       NaN
307498    0.0745
307499       NaN
307500       NaN
307501    0.0858
307502       NaN
307503       NaN
307504       NaN
307505    0.1700
307506    0.0172
307507    0.0451
307508    0.0894
307509       NaN
307510    0.0546
Name: BASEMENTAREA_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0383
1         0.0538
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.1010
14        0.1386
15           NaN
16           NaN
17           NaN
18        0.0640
19           NaN
20        0.0831
21           NaN
22        0.0825
23        0.0754
24        0.1509
25        0.0153
26        0.0092
27           NaN
28           NaN
29        0.0870
           ...
307481       NaN
307482    0.0417
307483    0.0000
307484       NaN
307485       NaN
307486    0.1990
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495       NaN
307496       NaN
307497       NaN
307498    0.0745
307499       NaN
307500       NaN
307501    0.0858
307502       NaN
307503       NaN
307504       NaN
307505    0.1700
307506    0.0172
307507    0.0451
307508    0.0894
307509       NaN
307510    0.0546
Name: BASEMENTAREA_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.9722
1         0.9851
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.9811
13        0.9806
14        0.9985
15           NaN
16           NaN
17           NaN
18        0.9881
19           NaN
20        0.9782
21           NaN
22        0.9786
23        0.9876
24        0.9861
25        0.9782
26        0.9732
27           NaN
28           NaN
29        0.9831
           ...
307481       NaN
307482    0.9737
307483    0.9747
307484       NaN
307485       NaN
307486    0.9782
307487       NaN
307488    0.9801
307489    0.9677
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.9871
307496       NaN
307497       NaN
307498    0.9891
307499       NaN
307500    0.9876
307501    0.9846
307502       NaN
307503       NaN
307504       NaN
307505    0.9861
307506    0.9782
307507    0.9727
307508    0.9816
307509    0.9772
307510    0.9881
Name: YEARS_BEGINEXPLUATATION_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.9722
1         0.9851
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.9811
13        0.9806
14        0.9985
15           NaN
16           NaN
17           NaN
18        0.9881
19           NaN
20        0.9782
21           NaN
22        0.9786
23        0.9876
24        0.9861
25        0.9782
26        0.9732
27           NaN
28           NaN
29        0.9831
           ...
307481       NaN
307482    0.9737
307483    0.9747
307484       NaN
307485       NaN
307486    0.9782
307487       NaN
307488    0.9801
307489    0.9677
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.9871
307496       NaN
307497       NaN
307498    0.9891
307499       NaN
307500    0.9876
307501    0.9846
307502       NaN
307503       NaN
307504       NaN
307505    0.9861
307506    0.9782
307507    0.9727
307508    0.9816
307509    0.9772
307510    0.9881
Name: YEARS_BEGINEXPLUATATION_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.6341
1         0.8040
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.7452
14        0.9804
15           NaN
16           NaN
17           NaN
18        0.8432
19           NaN
20        0.7125
21           NaN
22        0.7190
23        0.8367
24        0.8171
25        0.7125
26           NaN
27           NaN
28           NaN
29        0.7779
           ...
307481       NaN
307482    0.6537
307483    0.6668
307484       NaN
307485       NaN
307486       NaN
307487       NaN
307488       NaN
307489    0.5753
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495       NaN
307496       NaN
307497       NaN
307498    0.8563
307499       NaN
307500       NaN
307501       NaN
307502       NaN
307503       NaN
307504       NaN
307505    0.8171
307506    0.7125
307507    0.6406
307508    0.7583
307509       NaN
307510       NaN
Name: YEARS_BUILD_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.6341
1         0.8040
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.7452
14        0.9804
15           NaN
16           NaN
17           NaN
18        0.8432
19           NaN
20        0.7125
21           NaN
22        0.7190
23        0.8367
24        0.8171
25        0.7125
26           NaN
27           NaN
28           NaN
29        0.7779
           ...
307481       NaN
307482    0.6537
307483    0.6668
307484       NaN
307485       NaN
307486       NaN
307487       NaN
307488       NaN
307489    0.5753
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495       NaN
307496       NaN
307497       NaN
307498    0.8563
307499       NaN
307500       NaN
307501       NaN
307502       NaN
307503       NaN
307504       NaN
307505    0.8171
307506    0.7125
307507    0.6406
307508    0.7583
307509       NaN
307510       NaN
Name: YEARS_BUILD_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0144
1         0.0497
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.0587
14        0.1153
15           NaN
16           NaN
17           NaN
18        0.0018
19           NaN
20           NaN
21           NaN
22        0.0121
23        0.0000
24        0.0214
25        0.0010
26           NaN
27           NaN
28           NaN
29        0.0190
           ...
307481       NaN
307482    0.0038
307483    0.0000
307484       NaN
307485       NaN
307486       NaN
307487       NaN
307488       NaN
307489    0.0009
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0138
307496       NaN
307497       NaN
307498       NaN
307499       NaN
307500       NaN
307501       NaN
307502       NaN
307503       NaN
307504       NaN
307505    0.1445
307506    0.0172
307507    0.0022
307508    0.0124
307509       NaN
307510    0.0178
Name: COMMONAREA_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0144
1         0.0497
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.0587
14        0.1153
15           NaN
16           NaN
17           NaN
18        0.0018
19           NaN
20           NaN
21           NaN
22        0.0121
23        0.0000
24        0.0214
25        0.0010
26           NaN
27           NaN
28           NaN
29        0.0190
           ...
307481       NaN
307482    0.0038
307483    0.0000
307484       NaN
307485       NaN
307486       NaN
307487       NaN
307488       NaN
307489    0.0009
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0138
307496       NaN
307497       NaN
307498       NaN
307499       NaN
307500       NaN
307501       NaN
307502       NaN
307503       NaN
307504       NaN
307505    0.1445
307506    0.0172
307507    0.0022
307508    0.0124
307509       NaN
307510    0.0178
Name: COMMONAREA_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0000
1         0.0806
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0000
13        0.1611
14        0.4028
15           NaN
16           NaN
17           NaN
18        0.0000
19           NaN
20        0.0000
21           NaN
22        0.0000
23        0.1208
24        0.0000
25        0.0000
26        0.0000
27           NaN
28           NaN
29        0.1611
           ...
307481       NaN
307482    0.0000
307483    0.0000
307484       NaN
307485       NaN
307486    0.2417
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0806
307496       NaN
307497       NaN
307498    0.2417
307499       NaN
307500    0.0806
307501    0.0000
307502       NaN
307503       NaN
307504       NaN
307505    0.2417
307506    0.0806
307507    0.0000
307508    0.0000
307509       NaN
307510    0.0806
Name: ELEVATORS_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0000
1         0.0806
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0000
13        0.1611
14        0.4028
15           NaN
16           NaN
17           NaN
18        0.0000
19           NaN
20        0.0000
21           NaN
22        0.0000
23        0.1208
24        0.0000
25        0.0000
26        0.0000
27           NaN
28           NaN
29        0.1611
           ...
307481       NaN
307482    0.0000
307483    0.0000
307484       NaN
307485       NaN
307486    0.2417
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0806
307496       NaN
307497       NaN
307498    0.2417
307499       NaN
307500    0.0806
307501    0.0000
307502       NaN
307503       NaN
307504       NaN
307505    0.2417
307506    0.0806
307507    0.0000
307508    0.0000
307509       NaN
307510    0.0806
Name: ELEVATORS_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0690
1         0.0345
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.2069
13        0.1379
14        0.1724
15           NaN
16           NaN
17           NaN
18        0.1034
19           NaN
20        0.1379
21           NaN
22        0.2069
23        0.1034
24        0.3103
25        0.1379
26        0.0690
27           NaN
28           NaN
29        0.1379
           ...
307481       NaN
307482    0.0690
307483    0.0690
307484       NaN
307485       NaN
307486    0.2069
307487       NaN
307488       NaN
307489    0.0345
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0690
307496       NaN
307497       NaN
307498    0.1034
307499       NaN
307500    0.0345
307501    0.0345
307502       NaN
307503       NaN
307504       NaN
307505    0.2069
307506    0.0345
307507    0.1034
307508    0.2069
307509    0.0690
307510    0.0690
Name: ENTRANCES_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0690
1         0.0345
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.2069
13        0.1379
14        0.1724
15           NaN
16           NaN
17           NaN
18        0.1034
19           NaN
20        0.1379
21           NaN
22        0.2069
23        0.1034
24        0.3103
25        0.1379
26        0.0690
27           NaN
28           NaN
29        0.1379
           ...
307481       NaN
307482    0.0690
307483    0.0690
307484       NaN
307485       NaN
307486    0.2069
307487       NaN
307488       NaN
307489    0.0345
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0690
307496       NaN
307497       NaN
307498    0.1034
307499       NaN
307500    0.0345
307501    0.0345
307502       NaN
307503       NaN
307504       NaN
307505    0.2069
307506    0.0345
307507    0.1034
307508    0.2069
307509    0.0690
307510    0.0690
Name: ENTRANCES_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0833
1         0.2917
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.1667
13        0.3333
14        0.6667
15           NaN
16           NaN
17           NaN
18        0.0833
19           NaN
20        0.1667
21           NaN
22        0.1667
23        0.3750
24        0.1667
25        0.1667
26        0.0417
27           NaN
28           NaN
29        0.3333
           ...
307481       NaN
307482    0.1667
307483    0.0417
307484       NaN
307485       NaN
307486    0.3333
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.3333
307496       NaN
307497       NaN
307498    0.6667
307499       NaN
307500    0.6250
307501    0.0417
307502       NaN
307503       NaN
307504       NaN
307505    0.3333
307506    0.4583
307507    0.0833
307508    0.1667
307509    0.0417
307510    0.3750
Name: FLOORSMAX_MODE, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0833
1         0.2917
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.1667
13        0.3333
14        0.6667
15           NaN
16           NaN
17           NaN
18        0.0833
19           NaN
20        0.1667
21           NaN
22        0.1667
23        0.3750
24        0.1667
25        0.1667
26        0.0417
27           NaN
28           NaN
29        0.3333
           ...
307481       NaN
307482    0.1667
307483    0.0417
307484       NaN
307485       NaN
307486    0.3333
307487       NaN
307488       NaN
307489    0.0000
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.3333
307496       NaN
307497       NaN
307498    0.6667
307499       NaN
307500    0.6250
307501    0.0417
307502       NaN
307503       NaN
307504       NaN
307505    0.3333
307506    0.4583
307507    0.0833
307508    0.1667
307509    0.0417
307510    0.3750
Name: FLOORSMAX_MODE, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.1250
1         0.3333
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13        0.3750
14        0.7083
15           NaN
16           NaN
17           NaN
18        0.1250
19           NaN
20        0.0417
21           NaN
22        0.2083
23        0.4167
24        0.2083
25        0.0417
26           NaN
27           NaN
28           NaN
29        0.3750
           ...
307481       NaN
307482    0.2083
307483    0.0417
307484       NaN
307485       NaN
307486       NaN
307487       NaN
307488       NaN
307489    0.0417
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN

Name: AMT_REQ_CREDIT_BUREAU_HOUR, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_DAY, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_DAY, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    1.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_WEEK, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    1.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_WEEK, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         NaN
10        1.0
11        0.0
12        1.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        1.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    1.0
307500    1.0
307501    NaN
307502    0.0
307503    1.0
307504    NaN
307505    2.0
307506    NaN
307507    NaN
307508    1.0
307509    0.0
307510    2.0
Name: AMT_REQ_CREDIT_BUREAU_MON, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         0.0
6         1.0
7         0.0
8         0.0
9         NaN
10        1.0
11        0.0
12        1.0
13        0.0
14        NaN
15        0.0
16        0.0
17        NaN
18        0.0
19        0.0
20        NaN
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        1.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    1.0
307500    1.0
307501    NaN
307502    0.0
307503    1.0
307504    NaN
307505    2.0
307506    NaN
307507    NaN
307508    1.0
307509    0.0
307510    2.0
Name: AMT_REQ_CREDIT_BUREAU_MON, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         1.0
6         1.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        1.0
17        NaN
18        0.0
19        0.0
20        NaN
21        1.0
22        0.0
23        0.0
24        0.0
25        0.0
26        2.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    1.0
307487    1.0
307488    2.0
307489    1.0
307490    0.0
307491    1.0
307492    0.0
307493    1.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    1.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_QRT, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         0.0
1         0.0
2         0.0
3         NaN
4         0.0
5         1.0
6         1.0
7         0.0
8         0.0
9         NaN
10        0.0
11        0.0
12        0.0
13        0.0
14        NaN
15        0.0
16        1.0
17        NaN
18        0.0
19        0.0
20        NaN
21        1.0
22        0.0
23        0.0
24        0.0
25        0.0
26        2.0
27        0.0
28        0.0
29        NaN
         ...
307481    0.0
307482    0.0
307483    0.0
307484    NaN
307485    0.0
307486    1.0
307487    1.0
307488    2.0
307489    1.0
307490    0.0
307491    1.0
307492    0.0
307493    1.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    1.0
307500    0.0
307501    NaN
307502    0.0
307503    0.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    0.0
307509    0.0
307510    0.0
Name: AMT_REQ_CREDIT_BUREAU_QRT, Length: 307511, dtype: float64>
Max:  <bound method Series.max of 0         1.0
1         0.0
2         0.0
3         NaN
4         0.0
5         1.0
6         2.0
7         0.0
8         1.0
9         NaN
10        0.0
11        2.0
12        0.0
13        1.0
14        NaN
15        1.0
16        0.0
17        NaN
18        0.0
19        2.0
20        NaN
21        4.0
22        5.0
23        3.0
24        0.0
25        0.0
26        2.0
27        0.0
28        1.0
29        NaN
         ...
307481    3.0
307482    1.0
307483    5.0
307484    NaN
307485    0.0
307486    1.0
307487    8.0
307488    1.0
307489    2.0
307490    1.0
307491    7.0
307492    0.0
307493    7.0
307494    1.0
307495    1.0
307496    2.0
307497    6.0
307498    2.0
307499    0.0
307500    5.0
307501    NaN
307502    1.0
307503    2.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    1.0
307509    0.0
307510    1.0
Name: AMT_REQ_CREDIT_BUREAU_YEAR, Length: 307511, dtype: float64>
Min:  <bound method Series.min of 0         1.0
1         0.0
2         0.0
3         NaN
4         0.0
5         1.0
6         2.0
7         0.0
8         1.0
9         NaN
10        0.0
11        2.0
12        0.0
13        1.0
14        NaN
15        1.0
16        0.0
17        NaN
18        0.0
19        2.0
20        NaN
21        4.0
22        5.0
23        3.0
24        0.0
25        0.0
26        2.0
27        0.0
28        1.0
29        NaN
         ...
307481    3.0
307482    1.0
307483    5.0
307484    NaN
307485    0.0
307486    1.0
307487    8.0
307488    1.0
307489    2.0
307490    1.0
307491    7.0
307492    0.0
307493    7.0
307494    1.0
307495    1.0
307496    2.0
307497    6.0
307498    2.0
307499    0.0
307500    5.0
307501    NaN
307502    1.0
307503    2.0
307504    NaN
307505    0.0
307506    NaN
307507    NaN
307508    1.0
307509    0.0
307510    1.0
Name: AMT_REQ_CREDIT_BUREAU_YEAR, Length: 307511, dtype: float64>

In [ ]:
# 從上面的圖檢查的結果，至少這三個欄位好像有點可疑

# AMT_INCOME_TOTAL
# REGION_POPULATION_RELATIVE
# OBS_60_CNT_SOCIAL_CIRCLE

### Hints: Emprical Cumulative Density Plot, [ECDF](https://zh.wikipedia.org/wiki/%E7%BB%8F%E9%AA%8C%E5%88%86%E5%B8%83%E5%87%BD%E6%95%B0), [ECDF with Python](https://stackoverflow.com/questions/14006520/ecdf-in-python-without-step-function)

In [ ]:
# 最大值離平均與中位數很遠
print(app_train['AMT_INCOME_TOTAL'].describe())

# 繪製 Empirical Cumulative Density Plot (ECDF)
"""
YOUR CODE HERE
"""
cdf = 


plt.plot(list(cdf.index), cdf/cdf.max())
plt.xlabel('Value')
plt.ylabel('ECDF')
plt.xlim([cdf.index.min(), cdf.index.max() * 1.05]) # 限制顯示圖片的範圍
plt.ylim([-0.05,1.05]) # 限制顯示圖片的範圍

plt.show()

# 改變 y 軸的 Scale, 讓我們可以正常檢視 ECDF
plt.plot(np.log(list(cdf.index)), cdf/cdf.max())
plt.xlabel('Value (log-scale)')
plt.ylabel('ECDF')

plt.ylim([-0.05,1.05]) # 限制顯示圖片的範圍

plt.show()

## 補充：Normal dist 的 ECDF
![ecdf_normal](https://au.mathworks.com/help/examples/stats/win64/PlotEmpiricalCdfAndCompareWithSamplingDistributionExample_01.png)

In [ ]:
# 最大值落在分布之外
print(app_train['REGION_POPULATION_RELATIVE'].describe())

# 繪製 Empirical Cumulative Density Plot (ECDF)
"""
Your Code Here
"""
cdf = 


plt.plot(list(cdf.index), cdf/cdf.max())
plt.xlabel('Value')
plt.ylabel('ECDF')
plt.ylim([-0.05,1.05]) # 限制顯示圖片的範圍
plt.show()

app_train['REGION_POPULATION_RELATIVE'].hist()
plt.show()

app_train['REGION_POPULATION_RELATIVE'].value_counts()

# 就以這個欄位來說，雖然有資料掉在分布以外，也不算異常，僅代表這間公司在稍微熱鬧的地區有的據點較少，
# 導致 region population relative 在少的部分較為密集，但在大的部分較為疏漏

In [ ]:
# 最大值落在分布之外
print(app_train['OBS_60_CNT_SOCIAL_CIRCLE'].describe())

# 繪製 Empirical Cumulative Density Plot (ECDF)
"""
Your Code Here

cdf = 


plt.plot(list(cdf.index), cdf/cdf.max())
plt.xlabel('Value')
plt.ylabel('ECDF')
plt.xlim([cdf.index.min() * 0.95, cdf.index.max() * 1.05])
plt.ylim([-0.05,1.05]) # 限制顯示圖片的範圍
plt.show()
"""
app_train['OBS_60_CNT_SOCIAL_CIRCLE'].hist()
plt.show()
print(app_train['OBS_60_CNT_SOCIAL_CIRCLE'].value_counts().sort_index(ascending = False))

## 注意：當 histogram 畫出上面這種圖 (只出現一條，但是 x 軸延伸很長導致右邊有一大片空白時，代表右邊有值但是數量稀少。這時可以考慮用 value_counts 去找到這些數值

In [ ]:
# 把一些極端值暫時去掉，在繪製一次 Histogram
# 選擇 OBS_60_CNT_SOCIAL_CIRCLE 小於 20 的資料點繪製
"""
Your Code Here
"""
loc_a = 
loc_b = 

app_train.loc[loc_a, loc_b].hist()
plt.show()